<?php
    $_productCollection = $this->_getProductCollection();
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $theme = $this->helper('fengo');
    $_columnCount = $theme->getSetting('category_view/column_count');
    $_columnCount = ($_columnCount) ? $_columnCount : 3;
    //$gridClass = 'grid12-' . (int)12/$_columnCount;
    $gridClass = 'grid-columns cols-' . $_columnCount;
?>
<?php if(!$_collectionSize): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products style2">
    <?php echo $this->getToolbarHtml() ?>  

    <?php if($this->getMode()!='grid'): ?>
    <?php $_iterator = 0; ?>
    <ol class="products-list" id="products-list">
    <?php foreach ($_productCollection as $_product): ?>
        <li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
            <?php // Product Image ?>
            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280, 364); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                <?php if ($theme->getSetting('category_view/hover_image')) : ?>
                    <?php echo $theme->getHoverImgHtml($_product, 280, 364); ?>
                <?php endif; ?>
                <span class="product-labels">
                    <?php if (!$_product->isSaleable() && $theme->getSetting('category_view/out_of_stock')): ?>
                        <span class="out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                    <?php endif; ?>
                    <?php 
                        $date = date("Y-m-d 00:00:00");
                        $newtodate = $_product['news_to_date'];
                        $newfromdate = $_product['news_from_date'];
                    ?>
                    <?php if ($theme->getSetting('category_view/new')) {
                        if (isset($newfromdate)) { if (isset($newtodate) and $date >= $newfromdate and $date <= $newtodate) { ?>
                        <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                    <?php } else if (!isset($newtodate) and $date >= $newfromdate) { ?>
                        <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                    <?php } } else { if (isset($newtodate) and $date <= $newtodate) { ?>
                        <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                    <?php } } } ?>
                    <?php
                        $regularPrice = round($_product->getPrice());
                        $discountedPrice = round($_product->getFinalPrice());
                        if (($regularPrice != $discountedPrice) && $theme->getSetting('category_view/discount') && ($regularPrice != 0)) :
                    ?>
                        <span class="discount-code"><span><?php echo round(100*$discountedPrice/$regularPrice - 100).'%' ?></span></span>
                    <?php endif; ?>
                </span>
                <?php if ($theme->enabledQuickView()) : ?>
                <span data-target="<?php echo $this->getUrl('fengo/quickview/index', array('product_id' => $_product->getId()));?>" class="c-quickview"><span class="fa fa-search"></span><span class="quickview-label"><?php echo $this->__('Quick View');?></span></span>
                <?php endif; ?>
            </a>
            <?php // Product description ?>
            <div class="product-shop">
                <div class="f-fix">
                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                    <h2 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?></a></h2>
                    <div class="price-rating clearfix">
                    <?php echo $this->getPriceHtml($_product, true) ?>
                    <?php if($_product->getRatingSummary()): ?>
                        <div class="hide-below-960">
                            <?php echo $this->getReviewsSummaryHtml($_product, 'default') ?>
                        </div>
                        <div class="show-below-960">
                            <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        </div>
                    <?php endif; ?>
                    </div>
                    <div class="desc std">
                        <?php echo substr(strip_tags($_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description')), 0, 500) ?>
                        <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped ?>" class="link-learn"><?php echo $this->__('Learn More') ?></a>
                    </div>
                    <?php if($_product->isSaleable()): ?>
                        <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) : ?>
                            <p class="availability add-to-cart"><button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button btn-cart" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button></p>
                        <?php else: ?>
                            <p class="availability add-to-cart"><button type="button" title="<?php echo $this->__('Add to Bag') ?>" class="button btn-cart" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('Add to Bag') ?></span></span></button></p>
                            <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'></a>
                        <?php endif;  ?>
                    <?php endif; ?>
                    <ul class="add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('+ Add to Wishlist') ?></a></li>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <li><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('+ Add to Compare') ?></a></li>
                        <?php endif; ?>
                    </ul>
                </div>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
    <?php else: ?>
    <div class="grid-container">
        <ul class="products-grid">
        <?php foreach ($_productCollection as $_product): ?>
            <li class="<?php echo $gridClass; ?> grid12-6-below-960 grid-full-below-768 item">
                <div class="product-media">
                <?php if ($theme->enabledQuickView()) : ?>
                <a href="<?php echo $this->getUrl('fengo/quickview/index', array('product_id' => $_product->getId()));?>" class="c-quickview" title="<?php echo $this->__('Quick View');?>"><span class="fa fa-search"></span><span class="quickview-label"><?php echo $this->__('Quick View');?></span></a>
                <?php endif; ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280, 364); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <?php if ($theme->getSetting('category_view/hover_image')) : ?>
                            <?php echo $theme->getHoverImgHtml($_product, 280, 364); ?>
                        <?php endif; ?>                        
                        <span class="product-labels">
                            <?php if (!$_product->isSaleable() && $theme->getSetting('category_view/out_of_stock')): ?>
                                <span class="out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                            <?php endif; ?>
                            <?php 
                                $date = date("Y-m-d 00:00:00");
                                $newtodate = $_product['news_to_date'];
                                $newfromdate = $_product['news_from_date'];
                            ?>
                            <?php if ($theme->getSetting('category_view/new')) {
                                if (isset($newfromdate)) { if (isset($newtodate) and $date >= $newfromdate and $date <= $newtodate) { ?>
                                <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                            <?php } else if (!isset($newtodate) and $date >= $newfromdate) { ?>
                                <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                            <?php } } else { if (isset($newtodate) and $date <= $newtodate) { ?>
                                <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                            <?php } } } ?>
                            <?php
                                $regularPrice = round($_product->getPrice());
                                $discountedPrice = round($_product->getFinalPrice());
                                if (($regularPrice != $discountedPrice) && $theme->getSetting('category_view/discount') && ($regularPrice != 0)) :
                            ?>
                                <span class="discount-code"><span><?php echo round(100*$discountedPrice/$regularPrice - 100).'%' ?></span></span>
                            <?php endif; ?>
                        </span>
                    </a>
                </div>
                <div class="hover-section">
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <?php if ( !($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()) ) : ?>
                                <div class="add-to-bag grid12-6 no-gutter">
                                    <a title="<?php echo $this->__('Add to Bag') ?>" href="javascript:void(0);" onclick="setLocationAjax('<?php echo $this->getAddToCartUrl($_product) ?>','<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('ADD TO BAG') ?></span></span></a>

                                </div>
                            <?php else: ?>
                                <div class="add-to-bag grid12-6 no-gutter">
                                    <a title="<?php echo $this->__('Add to Bag') ?>" href="javascript:void(0);" onclick="showOptions('<?php echo $_product->getId()?>')"><span><span><?php echo $this->__('ADD TO BAG') ?></span></span></a>
                                </div>
                                <a href='<?php echo $this->getUrl('ajaxcart/index/options',array('product_id'=>$_product->getId()));?>' class='fancybox' id='fancybox<?php echo $_product->getId()?>' style='display:none'></a>
                            <?php endif;  ?>
                            <div class="more-info grid12-6 no-gutter">
                                <a title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" href="<?php echo $_product->getProductUrl() ?>"><span><span><?php echo $this->__('MORE INFO') ?></span></span></a>
                            </div>
                        <?php else: ?>
                            <p class="availability out-of-stock"><span><?php echo $this->__('OUT OF STOCK') ?></span></p>
                        <?php endif; ?>
                    </div>
                    <div class="grid-container add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <div class="grid12-6"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('+ Add to Wishlist') ?></a></div>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <div class="grid12-6" style="text-align:right"><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('+ Add to Compare') ?></a></div>
                        <?php endif; ?>
                    </div>
                </div>
                <div class="product-details">
                    <div class="grid-container">
                        <div class="grid12-8">
                            <h2 class="product-name">
                                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                            </h2>
                        </div>
                        <div class="grid12-4"><?php echo $this->getPriceHtml($_product, true) ?></div>
                    </div>
                    <div class="review">
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <?php endif; ?>
    <script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd','even','first','last'])</script> 

    <div class="toolbar-bottom">
        <?php echo $this->getToolbarHtml() ?>
    </div>   
</div>
<div class="ajaxcart_loading" style="display:none">
    <img src="<?php echo Mage::getDesign()->getSkinUrl('images/chestnut/layerednav/ajax-loader.gif') ?>" alt="Loading" />
</div>
<?php endif; ?>

<script type="text/javascript">
//<![CDATA[
var columnCount = <?php echo $_columnCount; ?>;
jQuery(function($) {
    // $('.fancybox').fancybox({
    //     hideOnContentClick : true,
    //     width: 410,
    //     padding: 0,
    //     overlayColor: '#000',
    //     overlayOpacity: 0.6,
    //     margin: 0,
    //     autoDimensions: false,
    //     type : 'iframe',
    //     showTitle: false,
    //     centerOnScroll: true,
    //     showCloseButton: true,
    //     scrolling: 'no',
    //     autoScale: true,
    //     onComplete: function(){
    //         $('#fancybox-frame').load(function() {
    //             $('#fancybox-content').height($(this).contents().find('body').height()+100);
    //             $.fancybox.resize();
    //             $.fancybox.center();
    //         });
    //     }
    // });

    $('.fancybox').magnificPopup({
        type: 'iframe',
        overflowY: 'scroll'
    });
});

function showOptions(id){
    jQuery('#fancybox'+id).trigger('click');
}

function setAjaxData(data,iframe){
    if(data.status == 'ERROR'){
        alert(data.message);
    }else{
        if(jQuery('.block-cart')){
            jQuery('.block-cart').replaceWith(data.cartsidebar);
        }
        if(jQuery('.header #mini-cart')){
            jQuery('.header #mini-cart').replaceWith(data.cartmini);
        }
        //jQuery.fancybox.close();
        jQuery.magnificPopup.close();
    }
}

function setLocationAjax(url,id){
    url += 'isAjax/1';
    url = url.replace("checkout/cart","ajaxcart/index");
    jQuery('.ajaxcart_loading').show();
    try {
        jQuery.ajax( {
            url : url,
            dataType : 'json',
            success : function(data) {
                jQuery('.ajaxcart_loading').hide();
                setAjaxData(data,false);
            }
        });
    } catch (e) {
    }
}
//]]>
</script>
