<?php $_product = $this->getProduct(); ?>
<?php $buttonTitle = $this->__('Add to Bag'); ?>
<?php if($_product->isSaleable()): ?>
    <div class="add-to-cart">
        <?php if(!$_product->isGrouped()): ?>
        <div id="qty_down_btn" class="qty_btn qty_down_btn" onclick="cqtyManager.qtyDown()"><i class="fa fa-angle-left"></i></div>
        <input type="text" name="qty" id="qty" maxlength="12" value="<?php echo $this->getProductDefaultQty() * 1 ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty" />
        <div id="qty_up_btn" class="qty_btn qty_up_btn" onclick="cqtyManager.qtyUp()"><i class="fa fa-angle-right"></i></div>
        <?php endif; ?>
        <button type="button" title="<?php echo $buttonTitle ?>" class="button btn-cart" onclick="productAddToCartForm.submit(this)"><span><span><?php echo $buttonTitle ?></span></span></button>
        <?php echo $this->getChildHtml('', true, true) ?>
    </div>
<?php endif; ?>
