<?php
    $_productCollection = $this->getProductCollectionCustom();
    $_productType = $this->_type;
    $_helper = $this->helper('catalog/output');
    $_collectionSize = $_productCollection->count();
    $_columnCount = 4;
    $_gridClass = 'grid12-' . (int)12 / $_columnCount;
    $theme = $this->_helper;
?>
<?php if(!$_collectionSize): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="home-products-grid style1">

    <div class="grid-container c-ias-container <?php echo $this->getAlias(); ?>">
        <ul class="grid-container">
        <?php foreach ($_productCollection as $_product): ?>
        <?php $_product->setOrigTypeId($_product->getTypeId());?>
        <?php $_product->setTypeId($_productType);?>
            <li class="<?php echo $_gridClass; ?> grid12-4-below-960 grid-full-below-768 c-ias-item item">
                <div class="product-media">
                    <?php if ($theme->enabledQuickView()) : ?>
                    <a href="<?php echo $this->getUrl('fengo/quickview/index', array('product_id' => $_product->getId()));?>" class="c-quickview" title="<?php echo $this->__('Quick View');?>"><span class="fa fa-search"></span><span class="quickview-label"><?php echo $this->__('Quick View');?></span></a>
                    <?php endif; ?>
                    <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(350, 455); ?>" width="270" height="350" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
                        <?php if ($theme->getSetting('category_view/hover_image')) : ?>
                            <?php echo $theme->getHoverImgHtml($_product, 350, 455); ?>
                        <?php endif; ?>
                        <span class="product-labels">
                            <?php if (!$_product->isSaleable() && $theme->getSetting('category_view/out_of_stock')): ?>
                                <span class="out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></span>
                            <?php endif; ?>
                            <?php 
                                $date = date("Y-m-d 00:00:00");
                                $newtodate = $_product['news_to_date'];
                                $newfromdate = $_product['news_from_date'];
                            ?>
                            <?php if ($theme->getSetting('category_view/new')) {
                                if (isset($newfromdate)) { if (isset($newtodate) and $date >= $newfromdate and $date <= $newtodate) { ?>
                                <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                            <?php } else if (!isset($newtodate) and $date >= $newfromdate) { ?>
                                <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                            <?php } } else { if (isset($newtodate) and $date <= $newtodate) { ?>
                                <span class="new-product"><span><?php echo $this->__('New') ?></span></span>
                            <?php } } } ?>
                            <?php
                                $regularPrice = round($_product->getPrice());
                                $discountedPrice = round($_product->getFinalPrice());
                                if (($regularPrice != $discountedPrice) && $theme->getSetting('category_view/discount') && ($regularPrice != 0)) :
                            ?>
                                <span class="discount-code"><span><?php echo round(100*$discountedPrice/$regularPrice - 100).'%' ?></span></span>
                            <?php endif; ?>
                        </span>
                    </a>
                </div>
                <div class="grid-container price-name">
                    <div class="grid12-8">
                        <h2 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
                        </h2>
                    </div>
                    <div class="grid12-4"><?php echo $this->getPriceHtml($_product, true) ?></div>
                </div>
                <div class="hover-content">
                    <div class="review">
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                    </div>
                    <div class="actions">
                        <?php if($_product->isSaleable()): ?>
                            <div class="add-to-bag grid12-6 no-gutter">
                                <a title="<?php echo $this->__('Add to Bag') ?>" href="<?php echo $this->getAddToCartUrl($_product) ?>"><span><span><?php echo $this->__('ADD TO BAG') ?></span></span></a>
                            </div>
                            <div class="more-info grid12-6 no-gutter">
                                <a title="<?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?>" href="<?php echo $_product->getProductUrl() ?>"><span><span><?php echo $this->__('MORE INFO') ?></span></span></a>
                            </div>
                        <?php else: ?>
                            <p class="availability out-of-stock grid-full"><span><?php echo $this->__('OUT OF STOCK') ?></span></p>
                        <?php endif; ?>
                    </div>
                    <div class="grid-container add-to-links">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <div class="grid12-6"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('+ Add to Wishlist') ?></a></div>
                        <?php endif; ?>
                        <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <div class="grid12-6" style="text-align:right"><a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('+ Add to Compare') ?></a></div>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ul>
        <?php if ($this->getTotalPageNum() > 1) : ?>
        <div class="c-ias-more clearfix">
            <div class="seperator"></div>
            <div class="show-more" onclick="cscroll.load('.c-ias-container.<?php echo $this->getAlias(); ?>', '.c-ias-item');"><?php echo $this->__('SHOW MORE'); ?></div>
            <div class="seperator"></div>
        </div>
        <div class="c-ias-loader clearfix">
            <div class="seperator"></div>
            <div class="loading-image">
                <img src="<?php echo $this->getSkinUrl('images/chestnut/layerednav/ajax-loader(1).gif'); ?>" alt="Loading" />
            </div>
            <div class="seperator"></div>
        </div>
        <?php endif; ?>
        <div class="home-products-grid-pager"><?php echo $this->getChildHtml('pager'); ?></div>
    </div>
</div>
<?php endif; ?>
<script type="text/javascript">
//<![CDATA[
function setAjaxData(data,iframe){
    if(data.status == 'ERROR'){
        alert(data.message);
    }else{
        if(jQuery('.block-cart')){
            jQuery('.block-cart').replaceWith(data.cartsidebar);
        }
        if(jQuery('.header #mini-cart')){
            jQuery('.header #mini-cart').replaceWith(data.cartmini);
        }
        //jQuery.fancybox.close();
        jQuery.magnificPopup.close();
    }
}
//]]>
</script>